### ISSUE TITLE
Headers are output in inconsistent order

### ISSUE THREAD

**Issue by alexmuller** [mikeedwards/po2json#65]
Hi,

I just started using po2json and I can see some behaviour where the headers are output in a different order on different runs (I'm not sure what the order depends on yet). This isn't really a problem but causes some unnecessarily noisy diffs when the JSON file is stored in version control.

https://github.com/mikeedwards/po2json/blob/v0.4.1/lib/parse.js#L62

Is this behaviour expected? Would you accept a pull request that returns the headers in a consistent order?

Thanks!

**Comment by mikeedwards** [comment]
Hmm, that's a good catch! I would absolutely accept a pull request for that! 

I'd only ask that you include a test with it, if possible, though that might be tricky if the issue is intermittent. At the very least, it should pass all existing tests (po2json has a lot of downstream users at this point.)

Thanks!
