### ISSUE TITLE
.po -> Module parse failed

### ISSUE THREAD

**Issue by dsoldo** [mikeedwards/po2json#79]
Full explanation of the problem (with screenshots, webpack configuration file and console.log output) you can find at this Stack Overflow question

https://stackoverflow.com/questions/53370456/webpack-module-parse-failed-po

**Comment by mikeedwards** [comment]
Super late to this as usual, but the Stack Overflow answer that has since been posted makes a lot of sense:

https://stackoverflow.com/a/57623001

I'd be loathe to change the output from a JSON string to an object, since a lot of downstream depends on getting a string (or, at least, have adapted their projects to expect a string.) In the spirit of not accidentally blowing up downstream with a change like this, I'm going to leave the behavior as is but leave this link to the SO answer. It might help to notify the po-loader folks about this, too, since they could update their docs with the answer:
https://github.com/perchlabs/po-loader
Someday, I'm just going to go to 2.0 and do a reset on all the weird little historical issues that keep this module from moving forward. Someday.
